// Generated by gencpp from file remote_control/set_controller.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SET_CONTROLLER_H
#define REMOTE_CONTROL_MESSAGE_SET_CONTROLLER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace remote_control
{
template <class ContainerAllocator>
struct set_controller_
{
  typedef set_controller_<ContainerAllocator> Type;

  set_controller_()
    : thrust(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  set_controller_(const ContainerAllocator& _alloc)
    : thrust(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _thrust_type;
  _thrust_type thrust;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::remote_control::set_controller_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::remote_control::set_controller_<ContainerAllocator> const> ConstPtr;

}; // struct set_controller_

typedef ::remote_control::set_controller_<std::allocator<void> > set_controller;

typedef boost::shared_ptr< ::remote_control::set_controller > set_controllerPtr;
typedef boost::shared_ptr< ::remote_control::set_controller const> set_controllerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::remote_control::set_controller_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::remote_control::set_controller_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace remote_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'remote_control': ['/home/crow/Documents/SDU-UAS-TX/remotecontrol_ws/src/remote_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::remote_control::set_controller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::remote_control::set_controller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_control::set_controller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_control::set_controller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_control::set_controller_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_control::set_controller_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::remote_control::set_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a86e32e294f019a20a1fc67767552aa8";
  }

  static const char* value(const ::remote_control::set_controller_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa86e32e294f019a2ULL;
  static const uint64_t static_value2 = 0x0a1fc67767552aa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::remote_control::set_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "remote_control/set_controller";
  }

  static const char* value(const ::remote_control::set_controller_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::remote_control::set_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This contains the procentage of stick movements for the channels\n\
float64 thrust\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::remote_control::set_controller_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::remote_control::set_controller_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thrust);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_controller_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::remote_control::set_controller_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::remote_control::set_controller_<ContainerAllocator>& v)
  {
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SET_CONTROLLER_H
